#!/usr/bin/env bash

# İleti kalıpları
export baslikProje="urtotm-bash"
export platformSec="Bir platform seçiniz"
export projeDizininiSec="Proje dizinini seçiniz"
export uretimDizininiSec="Projenin üretim dizinini seçiniz"
export yedekDiziniAdiniGir="Yedek görüntülerin kaydedileceği dizinin adını giriniz.\nDizin yoksa yaratılacaktır."
export islemSurdurulemiyor="işlem sürüdürülemiyor..."
export islemiSirasindaHata="işlemi sırasında bir hata oluştu."
export kurulumuSirasindaHata="kurulumu sırasında bir hata oluştu."
export gitReposuBulunamadi="Hedefte bir git dizini bulunamadı\nLütfen önce 'git init' ile bir git reposu ilkleyip\nbu kurulumu yeniden çalıştırınız."
export urunUzantisiniBelirt="Ürün uzantısını giriniz. Ör. hex, out vb."

# Platform tanımlamaları
declare -A platformlar=(
    [Üretim Otomasyonu Bash]=urtotm-bash
    [Android]=android-studio
    [Flutter]=flutter
    [MPLABX]=mplabx
    [Ceedling]=ceedling
)

# $1 Dönüş kodu
# $2 İşlem adı
donusKoduDegerlendir() {
    case $1 in
        1) mesajGoster hata "$baslikProje" \
            "$2 İşlemi sırasında bir şeyler ters gittiğinden $islemSurdurulemiyor"; exit 1 ;;
        0) echo "$2 işlemi başarılı" ;;
        *) mesajGoster hata "$baslikProje" \
            "$2 İşlemi sırasında beklenmeyen bir sorun oluştuğundan $islemSurdurulemiyor.\nHata kodu: $1"; exit 1 ;;
    esac
}

# $1 string1
# $2 string2
denetleBuyukKucukDuyarsiz() {
    [[ "${1^^}" == "${2^^}" ]] && [[ "${1,,}" == "${2,,}" ]]
}

# $1 platform
platformGecerli() {
    for p in "${!platformlar[@]}"; do
#         echo "platformGecerli: Sıradaki $p"
        if denetleBuyukKucukDuyarsiz "$1" "$p" || denetleBuyukKucukDuyarsiz "$1" "${platformlar[$p]}"; then
            echo "${platformlar[$p]}"
            return 0
        fi
    done
    return 1
}
